---
title: "Systems Analytics"
author: "Andrew Olson"
date: "October 10, 2018"
output: html_document
---

```{r setup, include=FALSE}
# Loading libraries needed for analysis
library(ggplot2)
library(gtable) #for plot layouts
library(grid) #for plot layouts
library(gridExtra) #for plot layouts
library(glmnet)
library(pROC)
library(plyr)
library(dplyr)
library(leaps)
library(reshape)
library(foreign)
library(plm) #for panel regression

#loading data and redefining "-" symbols as NA
ETANFload <- read.table("Data_Analysis_Spreadsheet.csv", header = TRUE, sep = ",", na.strings = "-")
#Removing unused Employment training variable
ETANFdata <- ETANFload[, c(1:16, 18, 19)]
#Cleaning the data - converting strings to numbers
ETANFdata <- mutate(ETANFdata, Year = as.factor(as.numeric(Year)), ETANF = as.numeric(gsub(",","",ETANF)), Snap_January = as.numeric(gsub(",","",Snap_January)),
                    SNAP_July = as.numeric(gsub(",","",SNAP_July)), Med_Income = as.numeric(Med_Income), Medicaid = as.numeric(gsub(",","",Medicaid)),
                    SSI = as.numeric(gsub(",","",SSI)), CHIP = as.numeric(gsub(",","",CHIP)), ED_Attain_HSandAbove = as.numeric(ED_Attain_HSandAbove),
                    Ed_Attain_BAandAbove = as.numeric(ED_Attain_HSandAbove), Population = as.numeric(gsub(",","",Population)))

#ETANFmelt <- melt(ETANFdata, id = c("County", "Year"))
#etanf.ts <- ts(ETANFdata, frequency = 1, start = c(2012), end = )

```


```{r}
### Data Visualization

# define palette
cpPalette <- c("#da3957","#57b951","#9d55ca","#9ab635","#6169d8","#c0ab39","#d360c8","#577c2b","#e13990","#55c1a1","#da562a","#4eacd7","#e7a13a","#5d7dc6","#c47d2a","#855099","#9cb36a","#ad3374","#398659","#d867ae","#7c722c","#b891d9","#965a2a","#e18db8","#cf9e68","#e35e84","#e57f5f","#9b5073","#b43c31","#dd8182","#a24951")
#plot of ETANF cases normalized by population
p1 <- ggplot(ETANFdata,aes(y = (ETANF/Population), x = Year, color = County)) + geom_point() + xlab("Year") + scale_color_manual(values =  cpPalette) 
p1
p2 <- ggplot(ETANFdata,aes(x = ETANF, fill = County)) + geom_bar() + xlab("ETANF") + scale_fill_manual(values =  cpPalette) + xlim(0, 300)
p2
p3 <- ggplot(ETANFdata,aes(y = ETANF, x = Year, color = County)) + geom_point() + 
  geom_smooth(data = ETANFdata, method = "glm", formula = ETANF~Year + County + PA_Region + SNAP_July + Medicaid + CHIP + LFPR + Med_Income + ED_Attain_HSandAbove + Ed_Attain_BAandAbove + Pov_Rate + Population) + xlab("Year") + scale_color_manual(values =  cpPalette) + ylim(0,300)
p3
```


```{r VariableSelection, echo=TRUE}
### Variable selection


#Set seed
set.seed(1234)
#subsetting data to remove extra location descriptors & missing records from dependent & Independent variables for variable selection
etanf.x <- na.omit(ETANFdata[, c(3:18)])
etanf.x2 <- na.omit(ETANFdata[, c(2:18)])
# fit the random forest
# rf1 <- cforest(ETANF ~ ., data= etanf.x, control=cforest_unbiased(mtry=2,ntree=20))

# AIC by crossvalidation for each variable selection method
testCV <- function(DATA){
  # combine two columns
  func.data <- data.frame(DATA)
  # Count the number of row of entire dataframe
  n.data <- nrow(func.data)
  # divide the number of rows in the dataframe into 8 groups
  folds <- split(sample(n.data, n.data ,replace=FALSE), as.factor(1:8))
    # aic list
    step.forward.aic <- rep(0,8)
    step.backward.aic <- rep(0,8)
    result<- data.frame("method" = character(), "aic" = numeric(), stringsAsFactors = FALSE)
  for (j in 1:8){
      test.data <- func.data[folds[[j]], ]
      n.test <-nrow(test.data)
      train.data <- func.data[-folds[[j]], ]
         #forward stepwise model
      null = glm(ETANF~1, data = na.omit(train.data), family = "poisson")
      full = glm(ETANF~., data = na.omit(train.data), family = "poisson")
      fwd.model <- step(null, scope = list(lower = null, upper = full), direction = "forward", trace = FALSE)
      step.forward.aic[j] <- AIC(fwd.model)
        #backward stepwise model
      bwd.model <- step(full, direction = "backward", trace = FALSE)
      step.backward.aic [j] <- AIC(bwd.model)
  }
    result <- rbind(result, data.frame(method = "forward", auc = mean(step.forward.aic)))
    result <- rbind(result, data.frame(method = "backward", auc = mean(step.backward.aic)))
    return(result)
}

test1 <- testCV(etanf.x)
test2 <- testCV(etanf.x2)

test1
test2
#Counting predictors for backward selection
null = glm(ETANF~1, data = etanf.x, family = "poisson")
full = glm(ETANF~., data = etanf.x, family = "poisson")
bwd.model <- step(full, direction = "backward", trace = FALSE)
bwd.model
null = glm(ETANF~1, data = etanf.x2, family = "poisson")
full = glm(ETANF~., data = etanf.x2, family = "poisson")
bwd.model2 <- step(full, direction = "backward", trace = FALSE)
bwd.model2
```

```{r Regression, message=FALSE, warning=FALSE}

#removing Butler, Greene, & McKean counties from data because of null values
to_keep <- which(ETANFdata$County != "Butler"& ETANFdata$County != "Greene"& ETANFdata$County != "McKean")
etanf.updated <- ETANFdata[c(to_keep),]
etanf.model <- glm(ETANF~Year + County + SNAP_July + Medicaid + CHIP + LFPR + Med_Income + ED_Attain_HSandAbove  + Pov_Rate + Population, data = etanf.updated, family = "poisson")

#summary(etanf.model)

etanf.updated$pred <- predict(etanf.model, etanf.updated, type = "response")

p1<- ggplot() +
  geom_line(data = etanf.updated, aes(x = Year, y = pred, color = County, group = County)) + 
  geom_point(data = ETANFdata, aes(x = Year, y = ETANF, color = County)) + ggtitle("Regression")
p2<- ggplot() +
  geom_line(data = etanf.updated, aes(x = Year, y = pred, color = County, group = County)) + ylim(0,350) +
  geom_point(data = ETANFdata, aes(x = Year, y = ETANF, color = County)) + ggtitle("Zoomed in Regression")


#Normalizing ETANF by population
etanf.new <-  etanf.updated
etanf.new$ETANF2 <- with(etanf.new, ETANF/Population)

new.model <- glm(ETANF2~Year + County + SNAP_July + Medicaid + CHIP + LFPR + Med_Income + ED_Attain_HSandAbove  + Pov_Rate, data = etanf.new, family = "poisson")
etanf.new$pred <- predict(new.model, etanf.new, type = "response")
p3<- ggplot() +
  geom_line(data = etanf.new, aes(x = Year, y = pred, color = County, group = County)) + 
  geom_point(data = ETANFdata, aes(x = Year, y = (ETANF/Population), color = County)) + ggtitle("Normalized Regression") 
p4<- ggplot() +
  geom_line(data = etanf.new, aes(x = Year, y = pred, color = County, group = County)) + ylim(0,.001) +
  geom_point(data = ETANFdata, aes(x = Year, y = (ETANF/Population), color = County)) + ggtitle("Zoomed in Normalized")
p1
p2
p3
p4

#smaller model
# small <- glm(ETANF~County+ Year + WIC + CHIP, data = etanf.updated, family = "poisson")
# etanf.updated$pred2 <- predict(small, etanf.updated, type = "response")
# small.normal <- glm(ETANF2~County + CHIP + WIC, data = etanf.new, family = "poisson")
# etanf.new$pred2<- predict(small.normal, etanf.new, type = "response")
# 
# p5<- ggplot() +
#   geom_line(data = etanf.updated, aes(x = Year, y = pred2, color = County, group = County)) + 
#   geom_point(data = ETANFdata, aes(x = Year, y = ETANF, color = County)) + ggtitle("Regression2")
# p6<- ggplot() +
#   geom_line(data = etanf.updated, aes(x = Year, y = pred2, color = County, group = County)) + ylim(0,350) +
#   geom_point(data = ETANFdata, aes(x = Year, y = ETANF, color = County)) + ggtitle("Zoomed in Regression2")
# p7<- ggplot() +
#   geom_line(data = etanf.new, aes(x = Year, y = pred2, color = County, group = County)) + 
#   geom_point(data = ETANFdata, aes(x = Year, y = (ETANF/Population), color = County)) + ggtitle("Normalized Regression2") 
# p8<- ggplot() +
#   geom_line(data = etanf.new, aes(x = Year, y = pred2, color = County, group = County)) + ylim(0,.001) +
#   geom_point(data = ETANFdata, aes(x = Year, y = (ETANF/Population), color = County)) + ggtitle("Zoomed in Normalized2")
# p5
# p6
# p7
# p8
```

```{r Panel} 
#scatterplot(ETANF ~ Year|County + SNAP_July + Medicaid + CHIP + LFPR + Med_Income + ED_Attain_HSandAbove + Ed_Attain_BAandAbove + Pov_Rate + Population, data = ETANFdata, boxplots = F, smooth = TRUE, reg.line = FALSE)
#scatterplot(ETANF ~ Year|County, data = ETANFdata, boxplots = FALSE, smooth = TRUE, reg.line = FALSE)
#abline(lm(ETANFdata$ETANF ~ ETANFdata$Year), lwd = 3, col = "red")
#coplot(ETANF ~ Year|County, type = "b", data = ETANFdata)

# panel <- plm(ETANF ~ SNAP_July + Medicaid + CHIP + LFPR + Med_Income + ED_Attain_HSandAbove + Pov_Rate + Population, data = na.omit(ETANFdata), index = c("County", "Year"), model = "within")
# 
# detect_lin_dep(panel)
# alias(panel, data = ETANFdata)
# summary(panel)
# 
# #pred.panel <- plm:::fitted_exp.plm(panel, data = ETANFdata)
# 
# panel2 <- plm(ETANF ~ SNAP_July + Medicaid + CHIP + LFPR + Med_Income + ED_Attain_HSandAbove + Pov_Rate + Population, data = na.omit(ETANFdata), index = c("County", "Year"), model = "pooling")
# summary(panel2)

#library(lme4)
#fit1 <- glmer(ETANF ~ SNAP_July + Medicaid + CHIP + LFPR + Med_Income + ED_Attain_HSandAbove + Pov_Rate + Population + (County|Year), data = ETANFdata, family= poisson(link= "log"))
```